config/routes.rb
Depot::Application.routes.draw do

   

  

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :products do
    get 'show' => :show
  end
  controller :users do
    get 'register' => :newuser
    post 'register' => :createuser    
  end
  
  controller :orders do
    get 'userorders' => :index_record
    get 'sendorder' => :sendorder
    get 'cancelorder' => :cancelorder
    get 'ordersrecord'=> :ordersrecord
    get 'userorderrecord' => :userorderrecord
    post 'destroyOneOrder' => :destroyOneOrder
    get 'destroyOneOrder' => :destroyOneOrder
  end
  
  controller :favourites do
    post 'create' => :create
    get 'create' => :create
  end
  
  controller :store do
    get 'show_search'      => :show_search
    post 'show_search'     => :show_search
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts  
    resources :messages 
    resources :favourites
    resources :comments
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end
  
  get "store/index"

  

  
  

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  # GET /favourites
  # GET /favourites.xml
  def index
    @favourites = Favourite.paginate :page => params[:page],:order => 'created_at desc',:per_page=>10,:conditions => "user_id = #{session[:user_id]}" 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favourites }
    end
  end

  # GET /favourites/1
  # GET /favourites/1.xml
  def show
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favourite }
    end
  end

  # GET /favourites/new
  # GET /favourites/new.xml
  def new
    @favourite = Favourite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favourite }
    end
  end

  # GET /favourites/1/edit
  def edit
    @favourite = Favourite.find(params[:id])
  end

  # POST /favourites
  # POST /favourites.xml
  def create
     @temp = Favourite.count(:conditions => ["product_id = ? and user_id = ?",params[:id],session[:user_id]])
    if @temp != 0
      redirect_to favourites_url
      return
    end
    @favourite = Favourite.new
    @favourite.product_id = params[:id]
    @favourite.user_id = session[:user_id]
    @favourite.save
    redirect_to favourites_url
    # respond_to do |format|
      # if @favourite.save
        # format.html { redirect_to(@favourite, :notice => 'Favourite was successfully created.') }
        # format.xml  { render :xml => @favourite, :status => :created, :location => @favourite }
      # else
        # format.html { render :action => "new" }
        # format.xml  { render :xml => @favourite.errors, :status => :unprocessable_entity }
      # end
    # end
  end

  # PUT /favourites/1
  # PUT /favourites/1.xml
  def update
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      if @favourite.update_attributes(params[:favourite])
        format.html { redirect_to(@favourite, :notice => 'Favourite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favourite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.xml
  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to(favourites_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_for(@favourite) do |f| %>
  <% if @favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% @favourite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing favourite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<h1><%= t('.list')%></h1>

<% @favourites.each do |favourite| %>
  <% @product = Product.find(favourite.product_id)%>
  <div class="entry">
  	<%= image_tag(@product.image_url) %>
  	<h3><%= link_to  @product.title ,{:controller => "products" ,:action => "show" ,:id => @product},:style=>"text-decoration:none"%></h3>
  	<%= sanitize @product.description %>
  	<div class="price_line">
  		<table>
  			<tr>
  				<td><span class="price"><%= number_to_currency(@product.price) %></span></td>
  				<td><% if @product.inventory != 0%>
  						<%= button_to t('.add') , line_items_path(:product_id => @product),
  								:remote => true %>  
   					<%end%>	</td>  				
  				<td>
  					<%= button_to t('.destroy'), favourite, :confirm => 'Are you sure?', :method => :delete %></td>
  			</tr>
  		</table>
    </div>
  </div>
<% end %>
   
<br />
<p><%= will_paginate @favourites%></p>
<%= link_to t('.back'), store_path%>

app/views/favourites/new.html.erb
<h1>New favourite</h1>

<%= render 'form' %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
 <% @user = User.find(@favourite.user_id)%>
 <%= @user.name %>
</p>

<% @product = Product.find(@favourite.product_id)%>
<p>
  <b>Product:</b> 
 <%= @product.title %>
</p>

<p>
	<b>Author:</b>
	<%= @product.author %>
</p>
	
<p>
	<b>Price:</b>
	<%=  number_to_currency(@product.price) %>
</p>


<!-- <%= link_to 'Edit', edit_favourite_path(@favourite) %> | -->
<%= link_to 'Back', favourites_path %>