config/routes.rb
Depot::Application.routes.draw do

   

  

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :products do
    get 'show' => :show
  end
  controller :users do
    get 'register' => :newuser
    post 'register' => :createuser    
  end
  
  controller :orders do
    get 'userorders' => :index_record
    get 'sendorder' => :sendorder
    get 'cancelorder' => :cancelorder
    get 'ordersrecord'=> :ordersrecord
    get 'userorderrecord' => :userorderrecord
    post 'destroyOneOrder' => :destroyOneOrder
    get 'destroyOneOrder' => :destroyOneOrder
  end
  
  controller :favourites do
    post 'create' => :create
    get 'create' => :create
  end
  
  controller :store do
    get 'show_search'      => :show_search
    post 'show_search'     => :show_search
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts  
    resources :messages 
    resources :favourites
    resources :comments
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end
  
  get "store/index"

  

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
  end
  
  validates :title, :description, :image_url,:inventory, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :inventory, :numericality => {:greater_than_or_equal_to => 0}
 
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with    => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, :only => :show
  # GET /products
  # GET /products.xml
  def index
    @products = Product.paginate :page=>params[:page], :order=>'created_at desc',:per_page =>5
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])
    if session[:user_id] 
      @user = User.find(session[:user_id])
    end
    @comments =Comment.paginate :page=>params[:page],:conditions => "product_id = #{@product.id}",:order=>'created_at asc',:per_page =>2
    @comment = Comment.new    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    # @product = Product.new(params[:product])
      # if request.get?
      @product = Product.new(params[:product])   
         
      @filename = save_file
      if @filename != nil 
          @product.image_url = "/uploads/#{@filename}"  
      else
          @product.image_url = "/images/logo.png"  
      end
    # else
      # @product = Product.new(params[:product]) 
    # end


    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])    
    @filename = save_file
     if @filename != nil 
        @product.image_url = "/uploads/#{@filename}"  
     end
     
     respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
     end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
  
  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
      format.xml {render :xml => @product}
    end
  end
  
   ############################################################################
  def configure_charsets  
     @headers["Content-Type"]="text/html;charset=utf-8" 
   end       
 
  def upload_file(file)  
     unless file.original_filename.empty?
       @filename=get_file_name(file.original_filename)   
       File.open("#{RAILS_ROOT}/public/uploads/#{@filename}", "wb") do |f|  
       f.write(file.read)  
       end  
       return @filename 
     end  
   end 
   
   def get_file_name(filename)  
     unless filename.nil?  
       Time.now.strftime("%Y%m%d%H%M%S") + '_' + filename  
     end  
   end  
 
   def save_file
     if params[:file] == nil
       return nil
     end
     
     if request.get? == false 
     # unless params[:file]['file'].original_filename.empty?
       if filename=upload_file(params[:file]['file'])  
         return filename  
       end  
     end 
      
   end  
end
  ############################################################################

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title,t('.title') %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :author,t('.author') %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description,t('.description') %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url,t('.image_url') %><br />   
    <%= file_field 'file', 'file'%>
  </div>
  
  <div class="field">
  	<%= f.label :inventory,t('.inventory')%><br/>
  	<%= f.text_field :inventory%>
  </div>
  <div class="field">
    <%= f.label :price,t('.price') %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit t('.ti')%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%= t('.edit')%></h1>

<%= form_tag({:action => 'update'}, :multipart => true) %>

	<%= render :partial => 'form' %>	
</form>

<%= link_to t('.show'), @product %> |
<%= link_to t('.back'), products_path %>

app/views/products/index.html.erb
<div id="product_list">
  <h1><%= t('.list')%></h1>

  <table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

      <td>
        <%= image_tag(product.image_url, :class => 'list_image') %>
      </td>

      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
                 :length => 80) %></dd>
        </dl>
      </td>

      <td class="list_actions">
        <%= link_to t('.show'), product %><br/>
        <%= link_to t('.edit'), edit_product_path(product) %><br/>
        <%= link_to t('.destroy'), product, 
                    :confirm => t('.confirm'),
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />


<%= link_to t('.new'), new_product_path %>
<p><%= will_paginate @products %></p>

app/views/products/new.html.erb
<h1>New product</h1>


<%= form_tag({:action => 'create'}, :multipart => true) %>

	<%= render :partial => 'form' %>
	<%= link_to 'Back', products_path %>
	
</form>

app/views/products/show.html.erb
<style>
	#ta
	{
		font-size:120%;
		background-color:#bfb;
		BORDER-BOTTOM:0px solid;
		BORDER-LEFT:0px solid;
		BORDER-RIGHT:0px solid;
		BORDER-TOP:0px solid;
	}
</style>

<p id="notice"><%= notice %></p>

<table>
	<tr valign= "top">
		<td style="width:20%">
			<p><%= image_tag @product.image_url %></p>		
		</td>
		<td style="width:80%">
  			<h2><b><%= @product.title %></b></h2>	
  			<b><%= t('.author')%>:<b><%= @product.author%>
			<p>			
  				<b><%= t('.inventory')%>:</b>   
  			 	<%= @product.inventory %>  
			</p>

			<p>
  				<b><%= t('.price')%>:</b>
  				<%= @product.price %>
			</p>
		</td>
	</tr>
	<tr>
		<td colspan = 2>			
  			<h1><%= t('.description')%></h1>
  			<%= @product.description %>
			
		</td>
	</tr>	
</table>


<br/>



<% if session[:user_id]%>
	<% if @user.user_type == 1 %>
		<%= link_to t('.edit'), edit_product_path(@product) %> |
		<%= link_to t('.back'), products_path %>
	<% else %>
		<%= link_to t('.back'), store_path %>
	<% end %>
<%else%>	
	<%= link_to t('.back'), store_path %>
<% end %>
<br/>
<br/>
<% if @comments != nil%>
<h1><%= t('.comments')%></h1>
<div style="width:100%">	
	
		<% @comments.each do |comment|%>
		<fieldset style="background-color:#bfb">
			<% @user = User.find(comment.user_id)%>
			<legend style="background-color:gray"><%= @user.name%><%=t('.s_comment')%>:</legend>
		
			 <textarea id="ta"  rows = "3" cols = "115" readonly="readonly"><%= comment.description%></textarea> 	
			 <hr width="100%">
			 <%=t('.comment_at')%> <%= comment.created_at%>		
			</fieldset>	
			<h5></h5>		
		<% end %>
	
</div>
<p><%= will_paginate @comments %></p>
<% end %>


<%= form_for @comment,:url => {:controller => "comments",:action => "create" , :id => @product} do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	


  <!-- <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id ,:value => @product.id%>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id,:value => session[:user_id] %>
  </div> -->

  <div class="field">
    <h1><%= f.label t('.Writting_Comment') %></h1><br />
    <%= f.text_area :description ,:rows =>5,:cols => 100%>
  </div>
  <div class="actions">
    <%= f.submit t('.commit')%>
  </div>
<% end %>