config/routes.rb
Depot::Application.routes.draw do

   

  

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :products do
    get 'show' => :show
  end
  controller :users do
    get 'register' => :newuser
    post 'register' => :createuser    
  end
  
  controller :orders do
    get 'userorders' => :index_record
    get 'sendorder' => :sendorder
    get 'cancelorder' => :cancelorder
    get 'ordersrecord'=> :ordersrecord
    get 'userorderrecord' => :userorderrecord
    post 'destroyOneOrder' => :destroyOneOrder
    get 'destroyOneOrder' => :destroyOneOrder
  end
  
  controller :favourites do
    post 'create' => :create
    get 'create' => :create
  end
  
  controller :store do
    get 'show_search'      => :show_search
    post 'show_search'     => :show_search
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts  
    resources :messages 
    resources :favourites
    resources :comments
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end
  
  get "store/index"

  

  
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:product_id=>product_id)
      line_items << current_item
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES =["Check","Credit card","Purchase order"]
  
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  validates :email, :format => {
    :with => %r{[0-9a-zA-Z]+@[0-9a-zA-Z]+\.[0-9a-zA-Z]+},
    :message=>'your email address is not legal'
  }

  
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
  end
  
  validates :title, :description, :image_url,:inventory, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :inventory, :numericality => {:greater_than_or_equal_to => 0}
 
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with    => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,:presence => true,:uniqueness => true
  
  validates :password,:confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
  
  after_destroy :ensure_an_admin_remains
  
  def ensure_an_admin_remains
    if User.count(:conditions=>"user_type=1").zero?
      raise "Can't delete last user"
    end
  end
  
  def get_username    
    self.name   
  end
  
  class << self
    def authenticate(name,password)
      if user = find_by_name(name)
        if user.hashed_password == encrypt_password(password,user.salt)
          user
        end
      end
    end
    
    def encrypt_password(password,salt)
       Digest::SHA2.hexdigest(password+"wible"+salt)
    end
  end
  
  def password=(password)
    @password = password
    
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password,salt)
    end
  end
  
  private
  
  def password_must_be_present
    errors.add(:password,"Missing password") unless hashed_password.present?
  end
  
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition,attributes = {},&block)
    if condition
      attributes["style"] = "display:none"
    end
    content_tag("div",attributes,&block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1><%= t('.welcome')%></h1>

<%= t('.it')%><%= Time.now %>
<%= t('.we')%> <%= pluralize(@total_orders,t('.order'))%>

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag "jquery", :type => "text/javascript"%>
  <%= javascript_include_tag "enlarge", :type => "text/javascript"%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<body id="store">
	<div id="banner">		
		<%= form_tag store_path,:class => 'locale' do %>
		<%= select_tag 'set_locale',options_for_select(LANGUAGES,I18n.locale.to_s),:onchange => 'this.form.submit()' %>
		<%= submit_tag 'submit'%>
		<%= javascript_tag "$$('.locale input').each(Element.hide)"%>
		<% end %>
		<%= image_tag("logo.png") %>
		<%= @page_title ||t('.title').html_safe%><!-- <label id="code.depot.e.title"/> -->
	</div>
	<div id="columns">		
		<div id="side">
			<%if session[:user_id]%>
				<% user = User.find(session[:user_id])%>
				<%= link_to user.name %>
			<%else%>
				<%= link_to t('.login'), login_path,:medthod => :new%>
			<%end%>
			<%= link_to t('.register'),register_path,:medthod => :newuser %><br/>		
			
			<%= form_tag show_search_url do%>
	  		<fieldset>
	  			<legend class="search"><%=t('.search')%></legend>
  					<%= text_field_tag :search_name,nil%>
	  				<%= submit_tag t('.go')%>
	  			</fieldset>
    		<%end%>

			<div id="cart">
				<% if @cart %>
			       <%= hidden_div_if(@cart.line_items.empty?,:id=>"cart") do %>
			       <%= render @cart %>
			       <% end %>
		        <% end %>
			</div>			
			<p></p>
			<%= link_to t('.home'),store_path %><br />			
			<%= link_to t('.news'),messages_path %><br />				
			<a href="/helpshell/admin.htm"><%= t('.admin_help')%></a><br/>	
			<a href="/helpshell/user.htm"><%= t('.user_help')%></a>><br/>	
			
			<% if session[:user_id] && session[:user_type] == 1%>
				<br />
				<%= link_to t('.favourite'), favourites_path%><br/>
				<%= link_to t('.my_order'),userorders_path%><br />	
				<%= link_to t('.my_order_record'),userorderrecord_path%><br/>
				<br/>
				<%= link_to t('.order'),orders_path %><br/>
				<%= link_to t('.product'), products_path %><br/>
				<%= link_to t('.user'),users_path %><br/>
				<%= link_to t('.order_record'),ordersrecord_path%><br/>
				<%= link_to t('.comment'),comments_path%><br/>				
				<br/>
				<%= button_to t('.logout'),logout_path,:method => :delete %>
			<% elsif session[:user_id] && session[:user_type] == 2%>
				<br />
				<%= link_to t('.favourite'), favourites_path%><br/>
				<%= link_to t('.my_order'),userorders_path%><br />	
				<%= link_to t('.my_order_record'),userorderrecord_path%><br/>
				<br/>
				<%= button_to t('.logout'),logout_path,:method => :delete %>
			<% end %>
		</div>
		<div id="main">		
			<%= yield %><!-- <label id="code.depot.e.include"/> -->
		</div>
	</div>
</body>
</html>

app/views/notifier/order_received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items %>

Order status: <% if @order.orderstatus == 0%>
    			<%= 'unsent'%>
    		  <% elsif @order.orderstatus == 1 %>
    		  	<%= 'sent'%>
    		  <% elsif @order.orderstatus == 2 %>
    	    	<%= 'cancel'%>
    		  <% end %>
We'll send you a separate e-mail when your order ships.

app/views/notifier/order_shipped.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items %>

<% if @order.orderstatus == 1 %>
    <%= 'Order status: sent'%>
    <%= 'We have sent goods!'%>
<% else @order.orderstatus == 2 %>
    <%= 'Order status:cancel'%>
    <%= 'Welcome to buy next time!'%>
<% end %>